/*CREANDO TABLA USUARIO*/
CREATE TABLE Usuario(
    ID_Usuario Number(11) GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR2(30) NOT NULL,
    Apellido VARCHAR2(30) NOT NULL,
    FechaNacimiento DATE NOT NULL,
    FechaRegistro DATE NOT NULL,
    Direccion VARCHAR2(30) NOT NULL,
    Telefono VARCHAR2(12) NOT NULL,
    Email VARCHAR2(30) NOT NULL,
    PRIMARY KEY(ID_Usuario)
);

/*CREANDO TABLA PRODUCTO*/
CREATE TABLE Producto(
    ID_Producto Number(11) GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR2(40) NOT NULL,
    Marca VARCHAR2(20) NOT NULL,
    Precio NUMBER (6) NOT NULL,
    PRIMARY KEY(ID_Producto)
);

/*CREANDO TABLA SEDE*/
CREATE TABLE Sede(
    ID_Sede Number(11) GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR2(30) NOT NULL,
    Direccion VARCHAR2(30) NOT NULL,
    PRIMARY KEY(ID_Sede)
);

/*CREANDO TABLA EMPLEADO*/
CREATE TABLE Empleado (
    ID_Empleado Number(11) GENERATED BY DEFAULT AS IDENTITY,
    ID_Sede Number(11),
    Nombre VARCHAR2(30) NOT NULL,
    Apellido VARCHAR2(30) NOT NULL,
    FechaNacimiento DATE NOT NULL,
    FechaIngreso DATE NOT NULL,
    Direccion VARCHAR2(30) NOT NULL,
    Telefono VARCHAR2(12) NOT NULL,
    Email VARCHAR2(30) NOT NULL,
    PRIMARY KEY(ID_Empleado),
    FOREIGN KEY(ID_Sede) REFERENCES Sede(ID_Sede)
);

/*CREANDO TABLA VENTA*/
CREATE TABLE Venta(
    ID_Venta NUMBER(11) GENERATED BY DEFAULT AS IDENTITY,
    ID_Usuario NUMBER(11),
    ID_Sede NUMBER(11),
    ID_Empleado NUMBER(11),
    FechaVenta DATE NOT NULL,
    N_Articulos NUMBER(3) NOT NULL,
    ID_Producto_1 NUMBER(11) NOT NULL,
    ID_Producto_2 NUMBER(11) NULL,
    ID_Producto_3 NUMBER(11) NULL,
    Modo VARCHAR2(20) NOT NULL,
    Tarjeta_Banco VARCHAR2(20) NULL,
    Precio NUMBER(6) NOT NULL,
    PRIMARY KEY(ID_Venta),
    FOREIGN KEY(ID_Usuario) REFERENCES Usuario(ID_Usuario),
    FOREIGN KEY(ID_Producto_1) REFERENCES Producto(ID_Producto),
    FOREIGN KEY(ID_Producto_2) REFERENCES Producto(ID_Producto),
    FOREIGN KEY(ID_Producto_3) REFERENCES Producto(ID_Producto),
    FOREIGN KEY(ID_Sede) REFERENCES Sede(ID_Sede),
    FOREIGN KEY(ID_Empleado) REFERENCES Empleado(ID_Empleado)
);

/*CREANDO TABLA PQRS*/
CREATE TABLE PQRS(
    ID_PQRS Number(11) GENERATED BY DEFAULT AS IDENTITY,
    ID_Usuario Number(11),
    Tipo VARCHAR(30) NOT NULL,
    FechaPQRS DATE NOT NULL,
    Motivo VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_PQRS),
    FOREIGN KEY(ID_Usuario)REFERENCES Usuario(ID_Usuario)
);

/*INSERTANDO USUARIOS*/

INSERT INTO Usuario ( Nombre, Apellido, FechaNacimiento, FechaRegistro, Direccion, Telefono, Email) 
VALUES ('David','Mendieta', TO_DATE('2001-09-19', 'YYYY-MM-DD'), TO_DATE('2023-04-26', 'YYYY-MM-DD'),'Avenida Calle 3 #16-46','3232012435','david.mendieta@gmail.com');
INSERT INTO Usuario ( Nombre, Apellido, FechaNacimiento, FechaRegistro, Direccion, Telefono, Email) 
VALUES ('Luis','Doncel', TO_DATE('1998-06-25', 'YYYY-MM-DD'), TO_DATE('2023-05-05', 'YYYY-MM-DD'),'Calle 5 #04-43','3222029626','luis.doncel@gmail.com');
INSERT INTO Usuario ( Nombre, Apellido, FechaNacimiento, FechaRegistro, Direccion, Telefono, Email)
VALUES ('Jhon','Montes', TO_DATE('1998-03-13', 'YYYY-MM-DD'), TO_DATE('2023-04-09', 'YYYY-MM-DD'),'Calle 63 #12-50','3144536130','jhon.montes@gmail.com');
INSERT INTO Usuario ( Nombre, Apellido, FechaNacimiento, FechaRegistro, Direccion, Telefono, Email)
VALUES ('Cristian','Rodriguez', TO_DATE('2001-09-12', 'YYYY-MM-DD'), TO_DATE('2023-04-09', 'YYYY-MM-DD'),'Calle 8 #10-10','3134555424','cristian.rodriguez@gmail.com');
INSERT INTO Usuario ( Nombre, Apellido, FechaNacimiento, FechaRegistro, Direccion, Telefono, Email)
VALUES ('Maicol','Perilla', TO_DATE('2000-07-01', 'YYYY-MM-DD'), TO_DATE('2023-09-12', 'YYYY-MM-DD'),'Calle 09 #09-98','3134278375','maicol.perilla@gmail.com');
INSERT INTO Usuario ( Nombre, Apellido, FechaNacimiento, FechaRegistro, Direccion, Telefono, Email)
VALUES ('Andres','Avila', TO_DATE('2006-07-14', 'YYYY-MM-DD'), TO_DATE('2024-01-12', 'YYYY-MM-DD'),'Calle 10 #10-90','3222707115','andres.avila@gmail.com');
INSERT INTO Usuario ( Nombre, Apellido, FechaNacimiento, FechaRegistro, Direccion, Telefono, Email)
VALUES ('Daniela','Barrera', TO_DATE('2002-04-07', 'YYYY-MM-DD'), TO_DATE('2023-06-20', 'YYYY-MM-DD'),'Cra 2 #10-04','3184122417','daniela.barrera@gmail.com');
INSERT INTO Usuario ( Nombre, Apellido, FechaNacimiento, FechaRegistro, Direccion, Telefono, Email)
VALUES ('Luisa','Paez', TO_DATE('2001-11-17', 'YYYY-MM-DD'), TO_DATE('2023-09-27', 'YYYY-MM-DD'),'Cra #73-44','3134830979','luisa.paez@gmail.com');
INSERT INTO Usuario ( Nombre, Apellido, FechaNacimiento, FechaRegistro, Direccion, Telefono, Email)
VALUES ('Paula','Paez', TO_DATE('1999-08-23', 'YYYY-MM-DD'), TO_DATE('2024-01-23', 'YYYY-MM-DD'),'Calle 3 #20-05','3158984355','paula.paez@gmail.com');
INSERT INTO Usuario ( Nombre, Apellido, FechaNacimiento, FechaRegistro, Direccion, Telefono, Email)
VALUES ('Jhenci','Mosquera', TO_DATE('2001-03-18', 'YYYY-MM-DD'), TO_DATE('2023-08-08', 'YYYY-MM-DD'),'Cra 23 #45-17','3158599416','jhenci.mosquera@gmail.com');
INSERT INTO Usuario ( Nombre, Apellido, FechaNacimiento, FechaRegistro, Direccion, Telefono, Email)
VALUES ('Carlos','Quintero', TO_DATE('2000-02-05', 'YYYY-MM-DD'), TO_DATE('2024-03-04', 'YYYY-MM-DD'),'Cra 25 #27-32','3138539416','carlos.quintero@gmail.com');

/*INSERTANDO PRODUCTOS*/

INSERT INTO Producto ( Nombre, Marca, Precio) VALUES ('Reloj Inteligente 8 Hombre Mujer','Smart Watch', 55000);
INSERT INTO Producto ( Nombre, Marca, Precio) VALUES ('Smart Band 8','Xiaomi', 152959);
INSERT INTO Producto ( Nombre, Marca, Precio) VALUES ('Reloj Digital Resistente','Raktors Max3', 49900);
INSERT INTO Producto ( Nombre, Marca, Precio) VALUES ('Reloj Smart Pro','Huawei', 99900);

/*INSERTANDO SEDES*/

INSERT INTO Sede ( Nombre, Direccion) VALUES ('Centro comercial Santafe','Calle 185 No. 45 - 03');
INSERT INTO Sede ( Nombre, Direccion) VALUES ('Centro comercial Bacata','Cl. 19 #5-30');
INSERT INTO Sede ( Nombre, Direccion) VALUES ('Centro comercial El Tintal','Av Ciudad de Cali # 6 - 37');


/*INSERTANDO EMPLEADOS*/

INSERT INTO Empleado (ID_Sede ,Nombre, Apellido, FechaNacimiento, FechaIngreso, Direccion, Telefono, Email)
VALUES (1,'Alejandra', 'Preciado', TO_DATE('1991-01-09', 'YYYY-MM-DD'), TO_DATE('2023-06-01', 'YYYY-MM-DD'),'Avenida Calle 185 #15-67','3217839914','alejandra.preciado@watch.com');
INSERT INTO Empleado (ID_Sede ,Nombre, Apellido, FechaNacimiento, FechaIngreso, Direccion, Telefono, Email)
VALUES (2,'Diego', 'Useche', TO_DATE('1994-03-06', 'YYYY-MM-DD'), TO_DATE('2023-04-01', 'YYYY-MM-DD'),'Calle 90 #17-34','3112234286','diego.useche@watch.com');
INSERT INTO Empleado (ID_Sede ,Nombre, Apellido, FechaNacimiento, FechaIngreso, Direccion, Telefono, Email)
VALUES (3,'Nelson', 'Calderon', TO_DATE('1989-11-19', 'YYYY-MM-DD'), TO_DATE('2023-10-17', 'YYYY-MM-DD'),'Avenida Calle 175 #100-97','3138537211','nelson.calderon@watch.com');
INSERT INTO Empleado (ID_Sede ,Nombre, Apellido, FechaNacimiento, FechaIngreso, Direccion, Telefono, Email)
VALUES (3,'Karen', 'Caipa', TO_DATE('1999-10-11', 'YYYY-MM-DD'), TO_DATE('2023-04-24', 'YYYY-MM-DD'),'Cra 1 #16-45','3165488326','karen.caipa@watch.com');

/*INSERTANDO VENTAS*/
INSERT INTO Venta (ID_Usuario ,ID_Sede, ID_Empleado, FechaVenta, N_Articulos, ID_Producto_1, ID_Producto_2, ID_Producto_3, Modo, Tarjeta_Banco, Precio)
VALUES (1,1,1, TO_DATE('2024-03-22', 'YYYY-MM-DD'), 1, 1, NULL, NULL, 'Tarjeta', 'Bancolombia',  55000);
INSERT INTO Venta (ID_Usuario ,ID_Sede, ID_Empleado, FechaVenta, N_Articulos, ID_Producto_1, ID_Producto_2, ID_Producto_3, Modo, Tarjeta_Banco, Precio)
VALUES (3,3,4, TO_DATE('2024-03-23', 'YYYY-MM-DD'), 2, 2, 1, NULL, 'Tarjeta', 'Davivienda', 207959);
INSERT INTO Venta (ID_Usuario ,ID_Sede, ID_Empleado, FechaVenta, N_Articulos, ID_Producto_1, ID_Producto_2, ID_Producto_3, Modo, Tarjeta_Banco, Precio)
VALUES (2,2,2, TO_DATE('2024-03-22', 'YYYY-MM-DD'), 1, 3, NULL, NULL, 'Tarjeta', 'Bancolombia',  49900);
INSERT INTO Venta (ID_Usuario ,ID_Sede, ID_Empleado, FechaVenta, N_Articulos, ID_Producto_1, ID_Producto_2, ID_Producto_3, Modo, Tarjeta_Banco, Precio)
VALUES (5,2,2, TO_DATE('2024-03-20', 'YYYY-MM-DD'), 3, 3, 4, 2, 'Tarjeta', 'Bancolombia',  302759);
INSERT INTO Venta (ID_Usuario ,ID_Sede, ID_Empleado, FechaVenta, N_Articulos, ID_Producto_1, ID_Producto_2, ID_Producto_3, Modo, Tarjeta_Banco, Precio)
VALUES (4,3,3, TO_DATE('2024-03-21', 'YYYY-MM-DD'), 1, 4, NULL, NULL, 'Tarjeta', 'Bancolombia',  99900);
INSERT INTO Venta (ID_Usuario ,ID_Sede, ID_Empleado, FechaVenta, N_Articulos, ID_Producto_1, ID_Producto_2, ID_Producto_3, Modo, Tarjeta_Banco, Precio) 
VALUES (6,1,1, TO_DATE('2024-03-20', 'YYYY-MM-DD'), 2, 1, 3, NULL, 'Efectivo', NULL,  104900);
INSERT INTO Venta (ID_Usuario ,ID_Sede, ID_Empleado, FechaVenta, N_Articulos, ID_Producto_1, ID_Producto_2, ID_Producto_3, Modo, Tarjeta_Banco, Precio)
VALUES (7,1,1, TO_DATE('2024-03-25', 'YYYY-MM-DD'), 1, 2, NULL, NULL, 'Tarjeta', 'Banco de Bogota',  152959);
INSERT INTO Venta (ID_Usuario ,ID_Sede, ID_Empleado, FechaVenta, N_Articulos, ID_Producto_1, ID_Producto_2, ID_Producto_3, Modo, Tarjeta_Banco, Precio)
VALUES (8,3,4, TO_DATE('2024-03-24', 'YYYY-MM-DD'), 2, 1, 4, NULL, 'Efectivo', NULL,  154900);
INSERT INTO Venta (ID_Usuario ,ID_Sede, ID_Empleado, FechaVenta, N_Articulos, ID_Producto_1, ID_Producto_2, ID_Producto_3, Modo, Tarjeta_Banco, Precio) 
VALUES (9,2,2, TO_DATE('2024-03-23', 'YYYY-MM-DD'), 1, 4, NULL, NULL, 'Tarjeta', 'Banco de Occidente',  99900);
INSERT INTO Venta (ID_Usuario ,ID_Sede, ID_Empleado, FechaVenta, N_Articulos, ID_Producto_1, ID_Producto_2, ID_Producto_3, Modo, Tarjeta_Banco, Precio)
VALUES (10,3,3, TO_DATE('2024-03-20', 'YYYY-MM-DD'), 3, 1, 4, 3, 'Efectivo', NULL, 204800);
INSERT INTO Venta (ID_Usuario ,ID_Sede, ID_Empleado, FechaVenta, N_Articulos, ID_Producto_1, ID_Producto_2, ID_Producto_3, Modo, Tarjeta_Banco, Precio)
VALUES (1,3,4, TO_DATE('2024-04-23', 'YYYY-MM-DD'), 3, 2, 3, 4, 'Tarjeta', 'Bancolombia', 302759);
INSERT INTO Venta (ID_Usuario ,ID_Sede, ID_Empleado, FechaVenta, N_Articulos, ID_Producto_1, ID_Producto_2, ID_Producto_3, Modo, Tarjeta_Banco, Precio)
VALUES (6,2,2, TO_DATE('2024-03-23', 'YYYY-MM-DD'), 1, 3, NULL, NULL, 'Efectivo', NULL,  49900);
INSERT INTO Venta (ID_Usuario ,ID_Sede, ID_Empleado, FechaVenta, N_Articulos, ID_Producto_1, ID_Producto_2, ID_Producto_3, Modo, Tarjeta_Banco, Precio)
VALUES (2,1,1, TO_DATE('2024-03-27', 'YYYY-MM-DD'), 1, 4, NULL, NULL, 'Tarjeta', 'Banco BBVA',  99900);
INSERT INTO Venta (ID_Usuario ,ID_Sede, ID_Empleado, FechaVenta, N_Articulos, ID_Producto_1, ID_Producto_2, ID_Producto_3, Modo, Tarjeta_Banco, Precio)
VALUES (8,2,2, TO_DATE('2024-03-30', 'YYYY-MM-DD'), 1, 1, NULL, NULL, 'Efectivo', NULL,  55000);
INSERT INTO Venta (ID_Usuario ,ID_Sede, ID_Empleado, FechaVenta, N_Articulos, ID_Producto_1, ID_Producto_2, ID_Producto_3, Modo, Tarjeta_Banco, Precio)
VALUES (9,3,4, TO_DATE('2024-04-01', 'YYYY-MM-DD'), 2, 3, 4, NULL, 'Tarjeta', 'Banco de Occidente', 141800);
INSERT INTO Venta (ID_Usuario ,ID_Sede, ID_Empleado, FechaVenta, N_Articulos, ID_Producto_1, ID_Producto_2, ID_Producto_3, Modo, Tarjeta_Banco, Precio)
VALUES (1,3,4, TO_DATE('2024-04-01', 'YYYY-MM-DD'), 2, 3, 4, NULL, 'Tarjeta', 'Bancolombia', 141800);

/*INSERTANDO PQRS*/
INSERT INTO PQRS (ID_Usuario, Tipo, FechaPQRS, Motivo) VALUES (1, 'Peticion', TO_DATE('2024-03-22', 'YYYY-MM-DD'), 'Servicio Excelente, Alejandra atiende de una manera exepcional');
INSERT INTO PQRS (ID_Usuario, Tipo, FechaPQRS, Motivo) VALUES (3, 'Reclamo', TO_DATE('2024-03-22', 'YYYY-MM-DD'),'El producto Smart Band 8 salio defectuoso');
INSERT INTO PQRS (ID_Usuario, Tipo, FechaPQRS, Motivo) VALUES (2, 'Sugerencia', TO_DATE('2024-03-23', 'YYYY-MM-DD'),'Deberian ser mas rapidos en la venta');
INSERT INTO PQRS (ID_Usuario, Tipo, FechaPQRS, Motivo) VALUES (6, 'Queja', TO_DATE('2024-03-21', 'YYYY-MM-DD'),'El gerente es muy altanero conmigo');
INSERT INTO PQRS (ID_Usuario, Tipo, FechaPQRS, Motivo) VALUES (10, 'Peticion',TO_DATE('2024-03-21', 'YYYY-MM-DD'), 'El asesor comercial Nelson es muy amable, me ayudo con la compra');
INSERT INTO PQRS (ID_Usuario, Tipo, FechaPQRS, Motivo) VALUES (7, 'Peticion',TO_DATE('2024-03-25', 'YYYY-MM-DD'), 'Que buen servicio');

/*DESCRIBIENDO ESTRUCTURA DE LA TABLA*/
DESCRIBE Usuario;
DESCRIBE Producto;
DESCRIBE Sede;
DESCRIBE Empleado;
DESCRIBE Venta;
DESCRIBE PQRS;

/*CONNSULTANDO TABLAS*/
SELECT * FROM Usuario;
SELECT * FROM Producto;
SELECT * FROM Sede;
SELECT * FROM Empleado;
SELECT * FROM Venta;
SELECT * FROM PQRS;

/*ELIMINANDO TABLAS*/
DROP TABLE Usuario;
DROP TABLE Producto;
DROP TABLE Sede;
DROP TABLE Empleado;
DROP TABLE Venta;
DROP TABLE PQRS;

DELETE FROM Usuario WHERE ID_Usuario = 22;


-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--Tablaspaces para datos de usuario
CREATE TABLESPACE usuarios_data
    DATAFILE 'C:\app\TABLES\usuarios_data.dbf' size 100M
    AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
  
--Tablaspaces para datos de producto  
CREATE TABLESPACE producto_data
    DATAFILE 'C:\app\TABLES\producto_data.dbf' size 100M
    AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
    
--Tablaspaces para datos de sede
CREATE TABLESPACE sede_data
    DATAFILE 'C:\app\TABLES\sede_data.dbf' size 100M
    AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
    
--Tablaspaces para datos de empleado 
CREATE TABLESPACE empleado_data
    DATAFILE 'C:\app\TABLES\producto_empleado.dbf' size 100M
    AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
    
--Tablaspaces para datos de venta  
CREATE TABLESPACE venta_data
    DATAFILE 'C:\app\TABLES\venta_data.dbf' size 100M
    AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
    
--Tablaspaces para datos de PQRS  
CREATE TABLESPACE pqrs_data
    DATAFILE 'C:\app\TABLES\producto_pqrs.dbf' size 100M
    AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;
    
--Tablaspaces para indices
CREATE TABLESPACE index_data
    DATAFILE 'C:\app\TABLES\index_data.dbf' size 50M
    AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

--Tablaspaces para redologs  
CREATE TABLESPACE REDO_LOGS_1 
    DATAFILE 'C:\app\TABLES\redo_logs_1.dbf' size 100M 
    AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

--MOVIENDO TABLAS A TABLESPACES PARA OPTIMIZAR EL ALMACENAMIENTO
ALTER TABLE Usuario MOVE TABLESPACE usuarios_data;
ALTER TABLE Producto MOVE TABLESPACE producto_data;
ALTER TABLE Sede MOVE TABLESPACE sede_data;
ALTER TABLE Empleado MOVE TABLESPACE empleado_data;
ALTER TABLE Venta MOVE TABLESPACE venta_data;
ALTER TABLE PQRS MOVE TABLESPACE pqrs_data;


------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

/*CREATE INDEX nombre_del_indice 
    ON nombre_de_la_table (columna1,columna2)*/
    
CREATE INDEX idx_usuario
    ON Usuario(Nombre);
    
CREATE INDEX idx_fecha_venta 
    ON Venta (FechaVenta); 
    
CREATE INDEX idx_usuario_fecha_registro 
    ON Usuario(FechaRegistro);
    
CREATE INDEX idx_empleado_id_sede 
    ON Empleado (ID_Sede);
    
CREATE INDEX idx_venta_id_producto_1
    ON Venta(ID_Producto_1)

CREATE INDEX idx_venta_id_producto_2
    ON Venta(ID_Producto_2)
   
CREATE INDEX idx_venta_id_producto_3
    ON Venta(ID_Producto_3)
   
CREATE INDEX idx_pqrs_id_usuario 
    ON PQRS(ID_Usuario);
    
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    
--CREANDO VISTAS
CREATE VIEW Vista_VentasPorUsuario AS
SELECT 
    u.ID_Usuario,
    u.Nombre || ' ' || u.Apellido AS NombreCompleto,
    COUNT(v.ID_Venta) AS TotalVentas,
    SUM(v.Precio) AS TotalVentaMonto
FROM Usuario u
LEFT JOIN Venta v ON u.ID_Usuario = v.ID_Usuario
GROUP BY u.ID_Usuario, u.Nombre, u.Apellido;

SELECT * FROM Vista_VentasPorUsuario; 

--CREANDO VISTAS 2
CREATE VIEW Detalles_PQRS AS
SELECT p.ID_PQRS, u.Nombre AS Nombre_Usuario, u.Apellido AS Apellido_Usuario, 
       p.Tipo, p.FechaPQRS, p.Motivo
FROM PQRS p
JOIN Usuario u ON p.ID_Usuario = u.ID_Usuario;

SELECT * FROM Detalles_PQRS;
    
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    
--CREANDO SEQUENCIAS
CREATE SEQUENCE seq_ID_Usuario start with 1 increment by 1;

INSERT INTO Usuario (ID_Usuario, Nombre, Apellido, FechaNacimiento, FechaRegistro, Direccion, Telefono, Email)
    VALUES (seq_ID_Usuario.nextval,'Daniela','Florez', TO_DATE('2006-06-24', 'YYYY-MM-DD'), 
    TO_DATE('2020-03-05', 'YYYY-MM-DD'),'Cra 27 #28-92','3197471474','daniela.florez@gmail.com');

CREATE SEQUENCE seq_ID_Producto start with 1 increment by 1;

INSERT INTO Producto (ID_Producto, Nombre, Marca, Precio)
VALUES (seq_ID_Producto.NEXTVAL, 'Reloj Inteligente 9 Hombre Mujer','Smart Watch', 60000);

CREATE SEQUENCE seq_ID_Sede start with 1 increment by 1; 

INSERT INTO Sede ( ID_Sede, Nombre, Direccion) VALUES (seq_ID_Sede.NEXTVAL, 'Centro comercial La Rosa','Av Ciudad de Mirll calle 9');

CREATE SEQUENCE seq_ID_Empleado start with 1 increment by 1;

INSERT INTO Empleado (ID_Sede ,Nombre, Apellido, FechaNacimiento, FechaIngreso, Direccion, Telefono, Email)
    VALUES (Seq_ID_Empleado.NEXTVAL,'Karen', 'Caipa', TO_DATE('1999-10-11', 'YYYY-MM-DD'), TO_DATE('2023-04-24', 'YYYY-MM-DD'),
    'Cra 1 #16-45','3165488326','karen.caipa@watch.com');
    
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    
--CREANDO TRIGGER

CREATE OR REPLACE TRIGGER Insert_Usuario
BEFORE INSERT ON Venta
    BEGIN 
        IF(TO_CHAR(SYSDATE, 'DY')IN ('SAT','SUN'))
        OR (TO_CHAR(SYSDATE, 'HH24:MI')NOT BETWEEN '07:00' AND '17:00')
        THEN RAISE_APPLICATION_ERROR(-20500, 'NO SE ENCUENTRA EN HORAS DE TRABAJAR, NO VENTAS DE RELOJES');
        END IF;
     END;   
     
INSERT INTO Venta (ID_Usuario ,ID_Sede, ID_Empleado, FechaVenta, N_Articulos, ID_Producto_1, ID_Producto_2, ID_Producto_3, Modo, Tarjeta_Banco, Precio) VALUES (2,3,4, TO_DATE('2024-04-01', 'YYYY-MM-DD'), 2, 3, 4, NULL, 'Tarjeta', 'Banco BBVA', 141800);

DROP TRIGGER Insert_Usuario;

ALTER INDEX SYSTEM.SYS_C008331 REBUILD;

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--CREANDO USUARIOS

ALTER SESSION SET "_ORACLE_SCRIPT" = true;

CREATE USER ADMIN_2 IDENTIFIED BY Mac0919;

--ASIGNANDO PRIVILEGIO PARA CONECTARSE A LA BASE DE DATOS
GRANT CONNECT, RESOURCE TO ADMIN_2;

ALTER USER ADMIN_2 IDENTIFIED BY MAC1010026970;

DROP USER ADMIN_2 CASCADE;

--CREAMOS UN ROL
CREATE ROLE rol_insertar;

--ASIGNAMOS EL ROL A UNA TABLA
GRANT INSERT ON Usuario TO rol_insertar;

--ASIGNAMOS ROL AL USUARIO 
GRANT rol_insertar TO ADMIN_2;


GRANT CREATE SESSION TO ADMIN_2;
GRANT CREATE TABLE TO ADMIN_2;
GRANT CREATE VIEW TO ADMIN_2;
GRANT CREATE SEQUENCE TO ADMIN_2;
GRANT CREATE PROCEDURE TO ADMIN_2;

-- REVOCAR ROL
REVOKE rol_insertar FROM ADMIN_2;

--ADMINISTRAR PRIVILEGIO
GRANT SELECT, INSERT, UPDATE, DELETE ON Usuario TO ADMIN_2;

/*CREATE ROLE rol_ejemplo
GRANT SELECT ON Usuario TO rol_ejemplo;

GRANT rol_ejemplo TO ADMIN_2;*/

AUDIT ALL BY ADMIN_2;

CREATE PROFILE PERFIL_SEGURO LIMIT 
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LIFE_TIME 90
PASSWORD_GRACE_TIME 7;

ALTER USER ADMIN_2 PROFILE PERFIL_SEGURO;

